-- SecureBank core schema.
-- Written in SQL that PostgreSQL and H2 (PostgreSQL mode, used by tests) both accept.

CREATE TABLE customers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100)             NOT NULL,
    email         VARCHAR(150)             NOT NULL,
    phone         VARCHAR(15)              NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    role          VARCHAR(20)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_role CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE accounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_number VARCHAR(12)              NOT NULL,
    customer_id    BIGINT                   NOT NULL,
    account_type   VARCHAR(20)              NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    balance        NUMERIC(19, 2)           NOT NULL DEFAULT 0,
    currency       VARCHAR(3)               NOT NULL,
    version        BIGINT                   NOT NULL DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    -- Last line of defence against overdrafts: even a bug in the service layer cannot commit one.
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0),
    CONSTRAINT ck_accounts_type CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    CONSTRAINT ck_accounts_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);

CREATE INDEX idx_accounts_customer_id ON accounts (customer_id);

CREATE TABLE bank_transactions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_reference  VARCHAR(30)              NOT NULL,
    type                   VARCHAR(20)              NOT NULL,
    status                 VARCHAR(20)              NOT NULL,
    amount                 NUMERIC(19, 2)           NOT NULL,
    source_account_id      BIGINT,
    destination_account_id BIGINT,
    description            VARCHAR(140),
    failure_reason         VARCHAR(255),
    initiated_by           BIGINT                   NOT NULL,
    request_id             VARCHAR(64),
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_bank_transactions_reference UNIQUE (transaction_reference),
    CONSTRAINT fk_txn_source_account FOREIGN KEY (source_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_txn_destination_account FOREIGN KEY (destination_account_id) REFERENCES accounts (id),
    CONSTRAINT ck_txn_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_txn_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER')),
    CONSTRAINT ck_txn_status CHECK (status IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_txn_has_account CHECK (source_account_id IS NOT NULL OR destination_account_id IS NOT NULL)
);

-- Statement queries filter by one account and sort by time, so the account column leads the index.
CREATE INDEX idx_txn_source_created ON bank_transactions (source_account_id, created_at);
CREATE INDEX idx_txn_destination_created ON bank_transactions (destination_account_id, created_at);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    action      VARCHAR(40)              NOT NULL,
    resource    VARCHAR(40)              NOT NULL,
    resource_id VARCHAR(64),
    status      VARCHAR(20)              NOT NULL,
    description VARCHAR(255),
    ip_address  VARCHAR(45),
    request_id  VARCHAR(64),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_customer_created ON audit_logs (customer_id, created_at);
CREATE INDEX idx_audit_action_created ON audit_logs (action, created_at);

CREATE TABLE idempotency_records (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(100)             NOT NULL,
    customer_id      BIGINT                   NOT NULL,
    operation        VARCHAR(20)              NOT NULL,
    request_hash     VARCHAR(64)              NOT NULL,
    status           VARCHAR(20)              NOT NULL,
    response_status  INTEGER,
    response_body    VARCHAR(4000),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at     TIMESTAMP WITH TIME ZONE,
    -- The database, not application code, guarantees one record per key per customer.
    CONSTRAINT uk_idempotency_customer_key UNIQUE (customer_id, idempotency_key),
    CONSTRAINT fk_idempotency_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_idempotency_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED'))
);
